branch-defaults:
  main:
    environment: web-frontend-startupcampus-env
    group_suffix: null
global:
  application_name: web-frontend
  branch: null
  default_ec2_keyname: webapp
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
