name: Deploy this application
on:
  push:
    branches: [main]

jobs:
  deploy_source:
    name: Test and deploying to server
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Create .env file
        run: |
          echo "$LOCAL_ENV" > .env.local
        env:
          LOCAL_ENV: "${{secrets.LOCAL_ENV}}"
      - name: Install npm dependencies and build
        run: |
          npm install 
          npm run build
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: web-frontend
          environment_name: web-frontend-startupcampus-env
          region: ap-southeast-1
